import type { Config } from 'tailwindcss';

// Design tokens consolidated from the "Luminous Scholar" design system
// (see luminous_scholar/DESIGN.md) — previously duplicated verbatim in an
// inline <script> tailwind.config block on every prototype HTML page.
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-surface': '#131b2e',
        'secondary-container': '#e0e3e5',
        'on-primary-container': '#fffbff',
        'primary-container': '#6063ee',
        'secondary-fixed': '#e0e3e5',
        'on-secondary-fixed': '#191c1e',
        'tertiary-fixed-dim': '#d0bcff',
        outline: '#767586',
        tertiary: '#6b38d4',
        surface: '#faf8ff',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed-variant': '#2f2ebe',
        'on-error': '#ffffff',
        'surface-container-low': '#f2f3ff',
        'surface-bright': '#faf8ff',
        'on-secondary': '#ffffff',
        'tertiary-container': '#8455ef',
        'inverse-on-surface': '#eef0ff',
        'on-surface-variant': '#464554',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#23005c',
        background: '#faf8ff',
        'error-container': '#ffdad6',
        'surface-container': '#eaedff',
        'primary-fixed-dim': '#c0c1ff',
        error: '#ba1a1a',
        'secondary-fixed-dim': '#c4c7c9',
        'surface-tint': '#494bd6',
        'surface-variant': '#dae2fd',
        primary: '#4648d4',
        'on-secondary-fixed-variant': '#444749',
        secondary: '#5c5f61',
        'on-primary': '#ffffff',
        'primary-fixed': '#e1e0ff',
        'on-secondary-container': '#626567',
        'surface-dim': '#d2d9f4',
        'outline-variant': '#c7c4d7',
        'surface-container-highest': '#dae2fd',
        'tertiary-fixed': '#e9ddff',
        'on-tertiary-container': '#fffbff',
        'on-error-container': '#93000a',
        'on-primary-fixed': '#07006c',
        'on-background': '#131b2e',
        'inverse-primary': '#c0c1ff',
        'surface-container-high': '#e2e7ff',
        'inverse-surface': '#283044',
        'on-tertiary-fixed-variant': '#5516be',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xl: '48px',
        gutter: '24px',
        '2xl': '80px',
        lg: '24px',
        md: '16px',
        'container-max': '1200px',
        sm: '8px',
        unit: '4px',
        xs: '4px',
      },
      fontFamily: {
        'label-sm': ['Inter', 'sans-serif'],
        'mono-code': ['JetBrains Mono', 'monospace'],
        'headline-md': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'display-lg-mobile': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'mono-code': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
} satisfies Config;
